/* A Thank You page
The page title should include Thank you for your order
 */
import Link from 'next/link';
import React from 'react';

export const metadata = {
  title: 'Thank you for your order',
  description: 'Generated by create next app',
};

export default function Checkout() {
  return (
    <main>
      <div>
        <h1>Thank you for your order</h1>
        <br />

        <p>Thank you, come again!</p>
        <br />
        <Link href="/products" data-test-id="continue-shopping">
          Continue Shopping
        </Link>
      </div>
    </main>
  );
}
