/* A Thank You page
The page title should include Thank you for your order
 */
import Link from 'next/link';
import React from 'react';
import styles from '../../page.module.scss';

export const metadata = {
  title: 'Thank you for your order',
  description: 'Generated by create next app',
};

export default function Checkout() {
  return (
    <main className={styles.main}>
      <div className={styles.container}>
        <h1>Thank you for your order</h1>
        <br />

        <p className={styles.center}>Thank you, come again!</p>
        <br />
        <Link href="/products" data-test-id="continue-shopping">
          Continue Shopping
        </Link>
      </div>
    </main>
  );
}
